repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python 3.8
  - repo: https://github.com/psf/black
    rev: 19.10b0 
    hooks:
      - id: black
        language_version: python 3.8